#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
'''Optimize the fourispacing to set the pme mesh part approciate. $1 is the pme mesh part value generated by last grompp command. $2 is the standard value. $3 is mdp file path.'''
import sys

pme_value = float(sys.argv[1])
pme_value_std = float(sys.argv[2])
mdp = sys.argv[3]
f = open(mdp)
content = f.read()
f.close()
lines = content.split('\n')
fourierspacing = ''
for i, line in enumerate(lines):
    key_value = line.split('\t=\t')
    if len(key_value) == 2 and key_value[0] == 'fourierspacing':
        fourierspacing = float(key_value[1])
        break
if fourierspacing == '':
    exit(1)
if pme_value > pme_value_std:
    fourierspacing += 0.01
elif pme_value < pme_value_std:
    fourierspacing -= 0.01
lines[i] = 'fourierspacing\t=\t%s' % round(fourierspacing, 2)
with open(mdp, 'w') as f:
    for line in lines:
        f.write(line + '\n')
print(round(fourierspacing, 2), end='')
